MODEL:
  REPO_ID: "TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF"
  URL: "https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"
  FILENAME: "tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"

VERSION: "0.0.1"